server:
  port: 8083  # 服务端口

#系统健康监控
management:
  health:
    mail:
      enabled: false
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: ["*"]
      base-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: web-service
  thymeleaf:
    prefix: classpath:/pages/
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  mvc:
    date-format: yyyy-MM-dd




feign:
  hystrix:
    enabled: true


resources:
  static-locations: ["/templates/","/resources/","/static/","/public/"]