server:
  port: 8081  # 服务端口
management:
  health:
    mail:
      enabled: false
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: ["*"]
      base-path: /actuator
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: web-service