server:
  port: 8081  # 服务端口

  #eureka:
client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://localhost:3306/newsmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.code.data.beans

