server:
  port: 8762
#配置中心配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/holiday-dog/newsmanager
          search-paths: config
          username: gaoganghua
          password: ggh09114515
      label: dev
